# Generated by Django 4.1.2 on 2022-11-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shortner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000)),
                ('decoded', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='URLData',
        ),
    ]
